apiVersion: apps/v1
kind: Deployment
metadata:
  name: ir-web-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ir-web-service
  template:
    metadata:
      labels:
        app: ir-web-service
    spec:
      containers:
        - name: ir-web-service
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5