apiVersion: v1
kind: Service
metadata:
  name: ir-web-service-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    app: ir-web-service